# Generated by Django 4.2.1 on 2023-05-08 22:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_item_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
