# Generated by Django 4.2.1 on 2023-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/items/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar/'),
        ),
    ]
