# Generated by Django 4.2.1 on 2023-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_rename_selected_answer_answer_answer_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='users_voted',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_count',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_choice',
            field=models.CharField(max_length=30),
        ),
    ]
