# Generated by Django 4.2.1 on 2023-05-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='userResponse',
        ),
    ]
