# Generated by Django 4.2.1 on 2023-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagePic',
            field=models.ManyToManyField(blank=True, related_name='messagePic', to='social.picture'),
        ),
    ]
