# Generated by Django 4.2.1 on 2023-05-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_remove_message_messagepic_message_messagepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replyCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeReply', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length='50')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='replyCount', to='social.reply'),
        ),
    ]
