# Generated by Django 4.2.1 on 2023-05-11 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_message_replycount_reply_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='reply', to='social.reply'),
        ),
        migrations.AlterField(
            model_name='message',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to='social.upvote'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replier', to=settings.AUTH_USER_MODEL),
        ),
    ]
