# Generated by Django 4.2.1 on 2023-05-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_message_reply_alter_message_upvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True, max_length='50', null=True),
        ),
    ]
